
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.jfree.ui.RefineryUtilities;

public class IncrementalFrame extends javax.swing.JFrame {
    addPhase newPhase = new addPhase(this, true);
    /**
     * Creates new form Try
     */
    public IncrementalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clockButton = new javax.swing.JLabel();
        calendarButton = new javax.swing.JLabel();
        riskIcon = new javax.swing.JLabel();
        addProject1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        projectImage = new javax.swing.JLabel();
        proyectLabel = new javax.swing.JLabel();
        userImage = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        resumenLabel = new javax.swing.JLabel();
        riesgosLabel = new javax.swing.JLabel();
        planificacionLabel = new javax.swing.JLabel();
        estimacionLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        copyrightSoftpro = new javax.swing.JLabel();
        contenedorPestañas = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftPro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reloj-circular.png"))); // NOI18N
        clockButton.setMaximumSize(new java.awt.Dimension(512, 512));
        clockButton.setMinimumSize(new java.awt.Dimension(512, 512));
        clockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clockButtonMouseClicked(evt);
            }
        });
        jPanel1.add(clockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        calendarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario (1).png"))); // NOI18N
        calendarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarButtonMouseClicked(evt);
            }
        });
        jPanel1.add(calendarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        riskIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alertas.png"))); // NOI18N
        riskIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riskIconMouseClicked(evt);
            }
        });
        jPanel1.add(riskIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        addProject1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir (1).png"))); // NOI18N
        addProject1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProject1MouseClicked(evt);
            }
        });
        jPanel1.add(addProject1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        projectImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pizarra.png"))); // NOI18N

        proyectLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        proyectLabel.setText("PROYECTO");

        userImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N

        profileLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        profileLabel.setText("MI PERFIL");

        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        resumenLabel.setText("Resumen general");
        resumenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resumenLabelMouseClicked(evt);
            }
        });

        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        riesgosLabel.setText("Gestión de riesgos");
        riesgosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riesgosLabelMouseClicked(evt);
            }
        });

        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        planificacionLabel.setText("Planificación");
        planificacionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planificacionLabelMouseClicked(evt);
            }
        });

        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        estimacionLabel.setText("Estimación");
        estimacionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estimacionLabelMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("Perfil");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setText("Cambiar rol");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Modificar datos");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Cambiar contraseña");

        logoutButton.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        logoutButton.setText("Cerrar sesión");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(riesgosLabel)
                            .addComponent(estimacionLabel)
                            .addComponent(planificacionLabel)
                            .addComponent(resumenLabel)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(logoutButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(projectImage)
                        .addGap(18, 18, 18)
                        .addComponent(proyectLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userImage)
                        .addGap(18, 18, 18)
                        .addComponent(profileLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userImage)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(profileLabel)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proyectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectImage))
                .addGap(18, 18, 18)
                .addComponent(resumenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estimacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planificacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riesgosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        copyrightSoftpro.setFont(new java.awt.Font("Calibri", 0, 8)); // NOI18N
        copyrightSoftpro.setText("Copyright © 2016 SoftPro Inc. Todos los derechos reservados.");

        javax.swing.GroupLayout contenedorPestañasLayout = new javax.swing.GroupLayout(contenedorPestañas);
        contenedorPestañas.setLayout(contenedorPestañasLayout);
        contenedorPestañasLayout.setHorizontalGroup(
            contenedorPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorPestañasLayout.setVerticalGroup(
            contenedorPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(copyrightSoftpro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(contenedorPestañas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorPestañas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightSoftpro)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calendarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseClicked

        setCurrentPanelPlanificacion();
        
    }//GEN-LAST:event_calendarButtonMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void estimacionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estimacionLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelEstimacion();
    }//GEN-LAST:event_estimacionLabelMouseClicked

    private void riesgosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riesgosLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelRiesgos();
    }//GEN-LAST:event_riesgosLabelMouseClicked

    private void planificacionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planificacionLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelPlanificacion();
    }//GEN-LAST:event_planificacionLabelMouseClicked

    private void resumenLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumenLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelResumen();
    }//GEN-LAST:event_resumenLabelMouseClicked

    private void clockButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockButtonMouseClicked
        // TODO add your handling code here:
        setCurrentPanelEstimacion();
    }//GEN-LAST:event_clockButtonMouseClicked

    private void riskIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riskIconMouseClicked
        // TODO add your handling code here:
        setCurrentPanelRiesgos();
    }//GEN-LAST:event_riskIconMouseClicked

    private void addProject1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProject1MouseClicked
        // TODO add your handling code here:
        newPhase.pack();
        RefineryUtilities.centerFrameOnScreen(newPhase);
        newPhase.setVisible(true);
    }//GEN-LAST:event_addProject1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
         }   catch (Exception e)    {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrumFrame().setVisible(true);
                
            }
        });
    }
    
    
    
    /*** Para los eventos, como se repite código,
       lo puse en métodos y los eventos los llama ***/
    public void setCurrentPanelEstimacion(){
        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 1, 13));
        
        //Diagrama de Gantt
        Gantt gantt = new Gantt ();
        gantt.pack();
        RefineryUtilities.centerFrameOnScreen(gantt);
        gantt.setVisible(true);
        
        displayPanel(contenedorPestañas, estimacion);
    }
    
    public void setCurrentPanelPlanificacion(){
        
        planificacionLabel.setFont(new java.awt.Font("Calibri", 1, 13));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        
        displayPanel(contenedorPestañas, planificacion);
    }
    
    private void setCurrentPanelResumen() {
        
        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 1, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
         
        
        displayPanel(contenedorPestañas, general);
        

    }

    private void setCurrentPanelRiesgos() {
        
        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 1, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        
        displayPanel(contenedorPestañas, riesgos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addProject1;
    private javax.swing.JLabel calendarButton;
    private javax.swing.JLabel clockButton;
    private javax.swing.JPanel contenedorPestañas;
    private javax.swing.JLabel copyrightSoftpro;
    private javax.swing.JLabel estimacionLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel planificacionLabel;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel projectImage;
    private javax.swing.JLabel proyectLabel;
    private javax.swing.JLabel resumenLabel;
    private javax.swing.JLabel riesgosLabel;
    private javax.swing.JLabel riskIcon;
    private javax.swing.JLabel userImage;
    // End of variables declaration//GEN-END:variables
    
    /* JPanels para planificación, estimación, riesgos y resumen general */
    private Planificacion planificacion = new Planificacion();
    private Estimacion estimacion = new Estimacion();
    private Riesgos riesgos = new Riesgos();
    private GeneralResumen general = new GeneralResumen();
   
    
    
    
    /*** Reemplaza los paneles que se muestran
      (sacado de como lo haría Beans dinamicamente, pero no funciona así) ***/
    private void displayPanel(JPanel contenedor, JPanel contenido) {
        contenedor.removeAll();

        GroupLayout layout = new GroupLayout(contenedor);
        contenedor.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(contenido, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(contenido, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }
}
