package softpro.View;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.RefineryUtilities;
import softpro.Model.State;
import softpro.Persistence.Database.SqliteInterface;
import static softpro.Persistence.IdGenerator.generateNewIdForTable;

public class Planificacion extends javax.swing.JPanel {

    /**
     * Creates new form pruebaGeneral
     */
    int index = 0;

    public Planificacion() {
        initComponents();
    }

    //  VIDEO MUY IMPORTANTE PARA EL AÑADIR MODIFICAR Y ELIMINAR EN LA TABLA. 
    //  LIKE Y SUPSCRIVANCE
    //  https://www.youtube.com/watch?v=KxzVF--FtUY
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserStoryToSprintDialog = new javax.swing.JDialog();
        addToSprintButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        addUserStoryToSprintDialog.setTitle("Añadir historia de usuario a Sprint");

        addToSprintButton.setText("Añadir a Sprint");
        addToSprintButton.setEnabled(false);
        addToSprintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToSprintButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SPRINT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESPONSABLE(S)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout addUserStoryToSprintDialogLayout = new javax.swing.GroupLayout(addUserStoryToSprintDialog.getContentPane());
        addUserStoryToSprintDialog.getContentPane().setLayout(addUserStoryToSprintDialogLayout);
        addUserStoryToSprintDialogLayout.setHorizontalGroup(
            addUserStoryToSprintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserStoryToSprintDialogLayout.createSequentialGroup()
                .addGroup(addUserStoryToSprintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserStoryToSprintDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addUserStoryToSprintDialogLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(addToSprintButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addUserStoryToSprintDialogLayout.setVerticalGroup(
            addUserStoryToSprintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserStoryToSprintDialogLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(addUserStoryToSprintDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToSprintButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PLANIFICACION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 13))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Inicio Est.", "Fin Est.", "Inicio Real", "Fin Real", "Prioridad", "Responsable", "Estado"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Añadir a Sprint");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*diálogo para Sprint*/
        addUserStoryToSprintDialog.pack();
        addUserStoryToSprintDialog.setVisible(true);
        RefineryUtilities.centerFrameOnScreen(addUserStoryToSprintDialog);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void addToSprintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToSprintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToSprintButtonActionPerformed

    private void updateTable() {
        //MOCK IMPLEMENTATION
        /* Object[] row = {name.getText(), 
                        inicioEst.getText(),
                        finEst.getText(),
                        inicioReal.getText(),
                        finReal.getText(),
                        priority.getText(),
                        responsable.getText(),
                        State.ToDo};
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.insertRow(index++, row);
        //FUTURE IMPLEMENTATION TODO _>
        String[] all = {"*"};
        SqliteInterface sqliteInterface = new SqliteInterface();
        List<HashMap<String, String>> result = sqliteInterface.selectFrom("tasks", all);
        for (HashMap<String, String> hashMap : result) {
            for (String key : hashMap.keySet()) {
                System.out.println(key + "---->" + hashMap.get(key));
            }
            System.out.println("\n");
        }*/
    }

//    //TODO - Remake this
//    private void insertTask(Task task){
//        Map<String, Object> taskToInsert = new HashMap<>();
//        taskToInsert.put("id", IdGenerator("features"));
//        taskToInsert.put("state", State.ToDo);
//        taskToInsert.put("feature", name.getText());
//        taskToInsert.put("estimated_duration", "XXXX");
//        taskToInsert.put("real_duration", "YYYY");
//        taskToInsert.put("responsible", responsable.getText());
//        taskToInsert.put("description", "This is a task about tasks");
//        taskToInsert.put("details", "Details about task");
//        SqliteInterface sqliteInterface = new SqliteInterface();
//        sqliteInterface.insertInto("tasks", taskToInsert);
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToSprintButton;
    private javax.swing.JDialog addUserStoryToSprintDialog;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
