package softpro.View;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.RefineryUtilities;
import softpro.Controller.CommandSet;
import softpro.Model.Project;
import softpro.Model.Scrum.ScrumProject;
import softpro.Persistence.Database.SqliteInterface;
import softpro.Persistence.ProjectLoader;

public class ScrumFrame extends javax.swing.JFrame {
    private ScrumProject project;
    private final CommandSet actionSet;
    addSprint newSprint = new addSprint(this, true);
    ArrayList<Project> projectsList = new ArrayList<>();

    /**
     * Creates new form Try
     */
    public ScrumFrame() {
        initComponents();
        this.actionSet = new CommandSet();
        dialogoProyectos.pack();
        RefineryUtilities.centerFrameOnScreen(dialogoProyectos);
        dialogoCrearProyecto.pack();
        RefineryUtilities.centerFrameOnScreen(dialogoCrearProyecto);
        project = ProjectLoader.loadScrumProject(2);
        estimacion = new Estimacion(project);
        planificacion = new Planificacion(project);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoProyectos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProyectos = new javax.swing.JTable();
        abrirProyecto = new javax.swing.JButton();
        añadirProyecto = new javax.swing.JButton();
        eliminarProyecto = new javax.swing.JButton();
        dialogoCrearProyecto = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        crearProyectoButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        clockButton = new javax.swing.JLabel();
        calendarButton = new javax.swing.JLabel();
        riskIcon = new javax.swing.JLabel();
        addSprintIcon = new javax.swing.JLabel();
        addProjectIcon = new javax.swing.JLabel();
        softproLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        projectImage = new javax.swing.JLabel();
        proyectLabel = new javax.swing.JLabel();
        userImage = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        resumenLabel = new javax.swing.JLabel();
        riesgosLabel = new javax.swing.JLabel();
        planificacionLabel = new javax.swing.JLabel();
        estimacionLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        copyrightSoftpro = new javax.swing.JLabel();
        contenedorPestañas = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        dialogoProyectos.setTitle("Proyectos");

        listaProyectos.setModel(this.createTableDataModel());
        listaProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaProyectosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaProyectos);

        abrirProyecto.setText("Abrir Proyecto");
        abrirProyecto.setEnabled(false);
        abrirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirProyectoActionPerformed(evt);
            }
        });

        añadirProyecto.setText("Crear proyecto");
        añadirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirProyectoActionPerformed(evt);
            }
        });

        eliminarProyecto.setText("Eliminar proyecto");
        eliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProyectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoProyectosLayout = new javax.swing.GroupLayout(dialogoProyectos.getContentPane());
        dialogoProyectos.getContentPane().setLayout(dialogoProyectosLayout);
        dialogoProyectosLayout.setHorizontalGroup(
            dialogoProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoProyectosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(añadirProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abrirProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogoProyectosLayout.setVerticalGroup(
            dialogoProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoProyectosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(dialogoProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoProyectosLayout.createSequentialGroup()
                        .addComponent(abrirProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(añadirProyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarProyecto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        dialogoCrearProyecto.setTitle("Crear proyecto");

        jLabel1.setText("Nombre proyecto:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        crearProyectoButton.setText("Crear");
        crearProyectoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProyectoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoCrearProyectoLayout = new javax.swing.GroupLayout(dialogoCrearProyecto.getContentPane());
        dialogoCrearProyecto.getContentPane().setLayout(dialogoCrearProyectoLayout);
        dialogoCrearProyectoLayout.setHorizontalGroup(
            dialogoCrearProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoCrearProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoCrearProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearProyectoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogoCrearProyectoLayout.setVerticalGroup(
            dialogoCrearProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoCrearProyectoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(dialogoCrearProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearProyectoButton))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoftPro");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reloj-circular.png"))); // NOI18N
        clockButton.setToolTipText("Estimación");
        clockButton.setMaximumSize(new java.awt.Dimension(512, 512));
        clockButton.setMinimumSize(new java.awt.Dimension(512, 512));
        clockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clockButtonMouseClicked(evt);
            }
        });
        jPanel1.add(clockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        calendarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario (1).png"))); // NOI18N
        calendarButton.setToolTipText("Planificación");
        calendarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarButtonMouseClicked(evt);
            }
        });
        jPanel1.add(calendarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        riskIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alertas.png"))); // NOI18N
        riskIcon.setToolTipText("Riesgos");
        riskIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riskIconMouseClicked(evt);
            }
        });
        jPanel1.add(riskIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        addSprintIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escalera.png"))); // NOI18N
        addSprintIcon.setToolTipText("Añadir Sprint");
        addSprintIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSprintIconMouseClicked(evt);
            }
        });
        jPanel1.add(addSprintIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        addProjectIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir (1).png"))); // NOI18N
        addProjectIcon.setToolTipText("Añadir proyecto");
        addProjectIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProjectIconMouseClicked(evt);
            }
        });
        jPanel1.add(addProjectIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        softproLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/softproLogo.png"))); // NOI18N
        jPanel1.add(softproLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 140, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        projectImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pizarra.png"))); // NOI18N

        proyectLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        proyectLabel.setText("PROYECTO");

        userImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N

        profileLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        profileLabel.setText("MI PERFIL");

        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        resumenLabel.setText("Resumen general");
        resumenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resumenLabelMouseClicked(evt);
            }
        });

        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        riesgosLabel.setText("Gestión de riesgos");
        riesgosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riesgosLabelMouseClicked(evt);
            }
        });

        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        planificacionLabel.setText("Planificación");
        planificacionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                planificacionLabelMouseClicked(evt);
            }
        });

        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        estimacionLabel.setText("Estimación");
        estimacionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estimacionLabelMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("Perfil");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Modificar datos");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Cambiar contraseña");

        logoutButton.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        logoutButton.setText("Salir");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(projectImage)
                        .addGap(18, 18, 18)
                        .addComponent(proyectLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userImage)
                        .addGap(18, 18, 18)
                        .addComponent(profileLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(estimacionLabel)
                                .addComponent(planificacionLabel)
                                .addComponent(resumenLabel)
                                .addComponent(jLabel13)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(riesgosLabel)
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userImage)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(profileLabel)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proyectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectImage))
                .addGap(18, 18, 18)
                .addComponent(resumenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estimacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planificacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riesgosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        copyrightSoftpro.setFont(new java.awt.Font("Calibri", 0, 8)); // NOI18N
        copyrightSoftpro.setText("Copyright © 2016 SoftPro Inc. Todos los derechos reservados.");

        javax.swing.GroupLayout contenedorPestañasLayout = new javax.swing.GroupLayout(contenedorPestañas);
        contenedorPestañas.setLayout(contenedorPestañasLayout);
        contenedorPestañasLayout.setHorizontalGroup(
            contenedorPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorPestañasLayout.setVerticalGroup(
            contenedorPestañasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Abrir proyecto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contenedorPestañas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(copyrightSoftpro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorPestañas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightSoftpro)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @SuppressWarnings("empty-statement")
    private DefaultTableModel createTableDataModel() {
        String[][] data = new String[100][10];
        int filas = 0;
        for (HashMap<String, String> project : selectProjects()){
            data[filas][0] = project.get("id");
            data[filas][1] = project.get("name");
            filas++;
        }
        String[] header = {"Id", "Nombre de Proyecto"};
        return new DefaultTableModel(data, header);
    }
    
    private void calendarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarButtonMouseClicked

        setCurrentPanelPlanificacion();

    }//GEN-LAST:event_calendarButtonMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void estimacionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estimacionLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelEstimacion();
    }//GEN-LAST:event_estimacionLabelMouseClicked

    private void riesgosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riesgosLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelRiesgos();
    }//GEN-LAST:event_riesgosLabelMouseClicked

    private void planificacionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_planificacionLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelPlanificacion();
    }//GEN-LAST:event_planificacionLabelMouseClicked

    private void resumenLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumenLabelMouseClicked
        // TODO add your handling code here:
        setCurrentPanelResumen();
    }//GEN-LAST:event_resumenLabelMouseClicked

    private void clockButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clockButtonMouseClicked
        // TODO add your handling code here:
        setCurrentPanelEstimacion();
    }//GEN-LAST:event_clockButtonMouseClicked

    private void riskIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riskIconMouseClicked
        // TODO add your handling code here:
        setCurrentPanelRiesgos();
    }//GEN-LAST:event_riskIconMouseClicked

    private void addSprintIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSprintIconMouseClicked
        // TODO add your handling code here:
        setCurrentPanelResumen();
    }//GEN-LAST:event_addSprintIconMouseClicked

    private void addProjectIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProjectIconMouseClicked
        dialogoProyectos.setVisible(true);
    }//GEN-LAST:event_addProjectIconMouseClicked

    private void abrirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirProyectoActionPerformed
        int projectID = Integer.parseInt(listaProyectos.getValueAt(listaProyectos.getSelectedRow(), 0).toString());
        project = ProjectLoader.loadScrumProject(projectID);
        estimacion = new Estimacion(project);
        ScrumFrame.this.setTitle("SoftPro - " + listaProyectos.getValueAt(listaProyectos.getSelectedRow(), 1).toString());
        dialogoProyectos.setVisible(false);
    }//GEN-LAST:event_abrirProyectoActionPerformed

    private void añadirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirProyectoActionPerformed
        // TODO add your handling code here:
        dialogoCrearProyecto.setVisible(true);
    }//GEN-LAST:event_añadirProyectoActionPerformed

    private void listaProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProyectosMouseClicked
        // TODO add your handling code here:
        abrirProyecto.setEnabled(true);
    }//GEN-LAST:event_listaProyectosMouseClicked

    private void crearProyectoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProyectoButtonActionPerformed
        HashMap<String, String> arguments = new HashMap<>();
        arguments.put("name",jTextField1.getText().trim());
        boolean r = actionSet.getAdministrativeAction(Operation.CREATE_PROJECT).execute(arguments);
        System.out.println(r);
        listaProyectos.setModel(createTableDataModel());
        jTextField1.setText("");
        dialogoCrearProyecto.setVisible(false);
    }//GEN-LAST:event_crearProyectoButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dialogoProyectos.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void eliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProyectoActionPerformed
        String index = (String) listaProyectos.getValueAt(listaProyectos.getSelectedRow(), 0);
        HashMap<String, String> arguments = new HashMap<>();
        arguments.put("projectID",index);
        boolean r = actionSet.getAdministrativeAction(Operation.DELETE_PROJECT).execute(arguments);
        System.out.println(r);
        listaProyectos.setModel(createTableDataModel());
        int firstProjectInList = Integer.parseInt(listaProyectos.getValueAt(0, 0).toString());
        project = ProjectLoader.loadScrumProject(firstProjectInList);
    }//GEN-LAST:event_eliminarProyectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrumFrame().setVisible(true);
            }
        });
    }

    /**
     * * Para los eventos, como se repite código, lo puse en métodos y los
     * eventos los llama **
     */
    public void setCurrentPanelEstimacion() {
        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 1, 13));

        displayPanel(contenedorPestañas, estimacion);
    }

    public void setCurrentPanelPlanificacion() {

        planificacionLabel.setFont(new java.awt.Font("Calibri", 1, 13));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));

        displayPanel(contenedorPestañas, planificacion);
    }

    private void setCurrentPanelResumen() {

        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 1, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));

        displayPanel(contenedorPestañas, general);

    }

    private void setCurrentPanelRiesgos() {

        planificacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        riesgosLabel.setFont(new java.awt.Font("Calibri", 1, 12));
        resumenLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        estimacionLabel.setFont(new java.awt.Font("Calibri", 0, 12));

        displayPanel(contenedorPestañas, riesgos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirProyecto;
    private javax.swing.JLabel addProjectIcon;
    private javax.swing.JLabel addSprintIcon;
    private javax.swing.JButton añadirProyecto;
    private javax.swing.JLabel calendarButton;
    private javax.swing.JLabel clockButton;
    private javax.swing.JPanel contenedorPestañas;
    private javax.swing.JLabel copyrightSoftpro;
    private javax.swing.JButton crearProyectoButton;
    private javax.swing.JDialog dialogoCrearProyecto;
    private javax.swing.JDialog dialogoProyectos;
    private javax.swing.JButton eliminarProyecto;
    private javax.swing.JLabel estimacionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable listaProyectos;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel planificacionLabel;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel projectImage;
    private javax.swing.JLabel proyectLabel;
    private javax.swing.JLabel resumenLabel;
    private javax.swing.JLabel riesgosLabel;
    private javax.swing.JLabel riskIcon;
    private javax.swing.JLabel softproLogo;
    private javax.swing.JLabel userImage;
    // End of variables declaration//GEN-END:variables

    /* JPanels para planificación, estimación, riesgos y resumen general */
    private Planificacion planificacion;
    private Estimacion estimacion;
    private Riesgos riesgos = new Riesgos();
    private GeneralResumen general = new GeneralResumen();

    /**
     * * Reemplaza los paneles que se muestran (sacado de como lo haría Beans
     * dinamicamente, pero no funciona así) **
     */
    private void displayPanel(JPanel contenedor, JPanel contenido) {
        contenedor.removeAll();

        GroupLayout layout = new GroupLayout(contenedor);
        contenedor.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(contenido, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(contenido, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }

    private Iterable<HashMap<String, String>> selectProjects() {
        return new SqliteInterface().selectFrom("projects", new String[]{"*"});
    }
}
