package softpro.View;

public enum Operation {
    ADD_STORY_TO_BACKLOG, ADD_STORY_TO_SPRINT, ADD_USER_TO_TEAM,
    ADD_PREDECESSOR_OF_STORY,
    
    CREATE_USER, CREATE_PROJECT, CREATE_SPRINT, CREATE_RISK,
    
    MODIFY_STORY, MODIFY_RISK, MODIFY_PROJECT_DATA, MODIFY_USER,
    
    REMOVE_USER_FROM_TEAM, REMOVE_PREDECESSOR_OF_STORY, 
    REMOVE_STORY_FROM_SPRINT, 
    
    DELETE_USER, DELETE_STORY, DELETE_SPRINT, DELETE_PROJECT, 
    DELETE_RISK,
}
